### PR TITLE
added SSN (NSSA) validation regex

### PR DESCRIPTION
**Pull request by nadchif**
I've added SSN validation regex

Please take a look and let me know if there are some changes I should make.

Thanks

### CODE REVIEW

**Comment by michaeldera** [comment]
Thank you very much @nadchif.... I do not really know if SSN numbers are consistent throughout... as in, if they share that same pattern for all number but if you are we can merge

**Review by michaeldera — COMMENTED** [review]
Looks good to me, just need confirmation from you that you are sure that thes are the general patterns for Social Security Numbers and we merge.

**Comment by nadchif** [comment]
Thank you for your positive response! Let me look for confirmation from a reliable official source and get back to you

**Comment by michaeldera** [comment]
Okay... I will also have a look. Will probably have a good position later today.

**Comment by michaeldera** [comment]
Merging this.... so far the info I got indicates this is fine.

**Review by michaeldera — APPROVED** [review]

**Comment by nadchif** [comment]
yoohoo!! 🕺 Thank you!

**Comment by michaeldera** [comment]
Thank you for contributing. Really appreciate it.

**Pull request merged**
